/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gestionbancaria;

import java.util.List;

/**
 *
 * @author user
 */
public class ConsultarCuenta extends javax.swing.JPanel {
private VentanaPrincipal ventana;
    /**
     * Creates new form ConsultarCuenta
     */
    public ConsultarCuenta(VentanaPrincipal ventana) {
        this.ventana=ventana;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlConsultarCuenta = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMostrar = new javax.swing.JTextArea();
        txtCedula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        pnlConsultarCuenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Digite la cédula del titular ");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlConsultarCuenta.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        txtMostrar.setColumns(20);
        txtMostrar.setRows(5);
        jScrollPane1.setViewportView(txtMostrar);

        pnlConsultarCuenta.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 500, 110));

        txtCedula.addActionListener(this::txtCedulaActionPerformed);
        pnlConsultarCuenta.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 270, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("Cédula:");
        pnlConsultarCuenta.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 100, -1));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(242, 242, 242));
        jButton1.setText("Regresar");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(this::jButton1ActionPerformed);
        pnlConsultarCuenta.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 240, 50));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI Semibold", 3, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(242, 242, 242));
        jButton2.setText("Consultar");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.addActionListener(this::jButton2ActionPerformed);
        pnlConsultarCuenta.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 240, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionbancaria/ConsultarCuenta1.jpg"))); // NOI18N
        pnlConsultarCuenta.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, -30, -1, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlConsultarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlConsultarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtMostrar.setText("");
        ventana.layout.show(ventana.panelCards, "panelPrincipal");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CuentaDao dao = new CuentaDao();
        int cedula = Integer.parseInt(txtCedula.getText());
        List<Cuenta> cuentas=dao.mostrarCuentas(cedula);
        for (Cuenta cuenta : cuentas) {
            String cuentaTipo = cuenta.getTipo_cuenta();
            double saldo = cuenta.getSaldo();
            String sucursal = cuenta.getSucursal();
            txtMostrar.append("Tipo de cuenta: "+cuentaTipo+" | Saldo: "+saldo+" | Sucursal: "+sucursal+"\n");
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlConsultarCuenta;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextArea txtMostrar;
    // End of variables declaration//GEN-END:variables
}
