/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gestionbancaria;

/**
 *
 * @author user
 */
public class CrearCuentaCorriente extends javax.swing.JPanel {
private VentanaPrincipal ventana;
    /**
     * Creates new form CrearCuentaCorriente
     */
    public CrearCuentaCorriente(VentanaPrincipal ventana) {
        initComponents();
        this.ventana=ventana;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCrearCorriente = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCuentaC = new javax.swing.JTextField();
        txtSaldoC = new javax.swing.JTextField();
        txtSucursalC = new javax.swing.JTextField();
        txtTitularC = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        pnlCrearCorriente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Crear nueva cuenta");
        pnlCrearCorriente.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("Tipo de cuenta: ");
        pnlCrearCorriente.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setText("Saldo:");
        pnlCrearCorriente.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 80, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(242, 242, 242));
        jLabel5.setText("Sucursal: ");
        pnlCrearCorriente.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(242, 242, 242));
        jLabel6.setText("Cédula del titular: ");
        pnlCrearCorriente.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));
        pnlCrearCorriente.add(txtCuentaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 240, -1));
        pnlCrearCorriente.add(txtSaldoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 240, -1));
        pnlCrearCorriente.add(txtSucursalC, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 240, -1));
        pnlCrearCorriente.add(txtTitularC, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 240, -1));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 3, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(242, 242, 242));
        jButton1.setText("Guardar y regresar");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        pnlCrearCorriente.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 240, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionbancaria/CuentaAhorro2.jpg"))); // NOI18N
        pnlCrearCorriente.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 740, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCrearCorriente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCrearCorriente, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String tipoCuenta = txtCuentaC.getText();
        double saldo = Double.parseDouble(txtSaldoC.getText());
        String sucursal = txtSucursalC.getText();
        int cedula = Integer.parseInt(txtTitularC.getText());
        CuentaCorriente cuenta = new CuentaCorriente(tipoCuenta,saldo,sucursal,cedula);
        CuentaDao dao = new CuentaDao();
        dao.crearCorriente(cuenta);
        ventana.layout.show(ventana.panelCards, "panelPrincipal");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel pnlCrearCorriente;
    private javax.swing.JTextField txtCuentaC;
    private javax.swing.JTextField txtSaldoC;
    private javax.swing.JTextField txtSucursalC;
    private javax.swing.JTextField txtTitularC;
    // End of variables declaration//GEN-END:variables
}
