/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gestionbancaria;

/**
 *
 * @author user
 */
public class CrearCuentaAhorros extends javax.swing.JPanel {
    private VentanaPrincipal ventana;
    /**
     * Creates new form CrearCuentaAhorros
     */
    public CrearCuentaAhorros(VentanaPrincipal ventana) {
        initComponents();
        this.ventana=ventana;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCrearAhorros = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblCuenta = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        lblSucursal = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        txtCuenta = new javax.swing.JTextField();
        txtSaldo = new javax.swing.JTextField();
        txtSucursal = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        pnlCrearAhorros.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Crear nueva Cuenta");
        pnlCrearAhorros.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        lblCuenta.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        lblCuenta.setForeground(new java.awt.Color(242, 242, 242));
        lblCuenta.setText("Tipo de cuenta: ");
        pnlCrearAhorros.add(lblCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        lblSaldo.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        lblSaldo.setForeground(new java.awt.Color(242, 242, 242));
        lblSaldo.setText("Saldo: ");
        pnlCrearAhorros.add(lblSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        lblSucursal.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        lblSucursal.setForeground(new java.awt.Color(242, 242, 242));
        lblSucursal.setText("Sucursal: ");
        pnlCrearAhorros.add(lblSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        lblCedula.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        lblCedula.setForeground(new java.awt.Color(242, 242, 242));
        lblCedula.setText("Cédula del titular: ");
        pnlCrearAhorros.add(lblCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));
        pnlCrearAhorros.add(txtCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 240, -1));
        pnlCrearAhorros.add(txtSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 240, -1));
        pnlCrearAhorros.add(txtSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 240, -1));
        pnlCrearAhorros.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 240, -1));

        btnRegresar.setBackground(new java.awt.Color(255, 0, 0));
        btnRegresar.setForeground(new java.awt.Color(242, 242, 242));
        btnRegresar.setText("Guardar y regresar");
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);
        pnlCrearAhorros.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 240, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionbancaria/CuentaAhorro2.jpg"))); // NOI18N
        pnlCrearAhorros.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCrearAhorros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCrearAhorros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        String tipoCuenta = txtCuenta.getText();
        double saldo = Double.parseDouble(txtSaldo.getText());
        String sucursal = txtSucursal.getText();
        int cedula = Integer.parseInt(txtCedula.getText());
        CuentaAhorros cuenta = new CuentaAhorros(tipoCuenta,saldo,sucursal,cedula);
        CuentaDao dao = new CuentaDao();
        dao.crearAhorros(cuenta);
        txtCuenta.setText("");
        txtSaldo.setText("");
        txtSucursal.setText("");
        txtCedula.setText("");
        ventana.layout.show(ventana.panelCards, "panelPrincipal");
    }//GEN-LAST:event_btnRegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblCuenta;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblSucursal;
    private javax.swing.JPanel pnlCrearAhorros;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCuenta;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JTextField txtSucursal;
    // End of variables declaration//GEN-END:variables
}
