/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gestionbancaria;

import java.util.List;

/**
 *
 * @author user
 */
public class MostrarUsuarios extends javax.swing.JPanel {
    private VentanaPrincipal ventana;
    /**
     * Creates new form MostrarUsuarios
     */
    public MostrarUsuarios(VentanaPrincipal ventana) {
        this.ventana=ventana;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMostrarUsuarios = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtUsuarios = new javax.swing.JTextArea();
        btnUsuarios = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();

        pnlMostrarUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuarios Registrados");
        pnlMostrarUsuarios.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, -1));

        txtUsuarios.setColumns(20);
        txtUsuarios.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        txtUsuarios.setRows(5);
        jScrollPane1.setViewportView(txtUsuarios);

        pnlMostrarUsuarios.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 630, 320));

        btnUsuarios.setBackground(new java.awt.Color(255, 0, 0));
        btnUsuarios.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        btnUsuarios.setText("Mostrar usuarios");
        btnUsuarios.addActionListener(this::btnUsuariosActionPerformed);
        pnlMostrarUsuarios.add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 550, 200, 60));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jButton1.setText("Volver al inicio");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        pnlMostrarUsuarios.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 550, 200, 60));

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionbancaria/imagenusuarios1.jpg"))); // NOI18N
        lblImagen.setPreferredSize(new java.awt.Dimension(1200, 700));
        pnlMostrarUsuarios.add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMostrarUsuarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMostrarUsuarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtUsuarios.setText("");
        ventana.layout.show(ventana.panelCards, "panelPrincipal");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
         ClienteDao dao = new ClienteDao();
         List<Cliente> clientes = dao.mostrarClientes();
         for (Cliente cliente  : clientes) {
            String nombre = cliente.getNombre();
            String apellido = cliente.getApellido();
            String correo = cliente.getCorreoElectronico();
            int cedula = cliente.getCedula();
            
            txtUsuarios.append("Nombre: "+nombre+" | Apellido: "+apellido+" | Correo: "+correo+" | Cédula: "+cedula+"\n");
            
            
            
        }
             }//GEN-LAST:event_btnUsuariosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JPanel pnlMostrarUsuarios;
    private javax.swing.JTextArea txtUsuarios;
    // End of variables declaration//GEN-END:variables
}
