/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gestionbancaria;

/**
 *
 * @author user
 */
public class PanelRegistrarCliente extends javax.swing.JPanel {

    /**
     * Creates new form PanelRegistrarCliente
     */
    public PanelRegistrarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblTituloRegis = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblNombre1 = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        lblCorreo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        lblNombre.setText("Nombre:");
        add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 90, -1));

        lblTituloRegis.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        lblTituloRegis.setText("Registrar Cliente");
        add(lblTituloRegis, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 240, -1));
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 230, -1));

        lblNombre1.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        lblNombre1.setText("Nombre:");
        add(lblNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 90, -1));

        lblApellido.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        lblApellido.setText("Apellido:");
        add(lblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 90, -1));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 230, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel1.setText("Cédula: ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, -1, -1));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 230, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel2.setText("Correo: ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 80, -1));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, 230, -1));

        btnRegresar.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        btnRegresar.setText("Guardar y Regresar ");
        add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        lblCorreo.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        lblCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionbancaria/registroUsuario.jpg"))); // NOI18N
        add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 450));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblTituloRegis;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
