/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gestionbancaria;

/**
 *
 * @author user
 */
public class Retirar extends javax.swing.JPanel {
private VentanaPrincipal ventana;
    /**
     * Creates new form Retirar
     */
    public Retirar(VentanaPrincipal ventana) {
        this.ventana=ventana;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlRetirar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtRespuesta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlRetirar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("Centro de Retiro");
        pnlRetirar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("Digite la cuenta ID a la cual se le va a realizar el retiro: ");
        pnlRetirar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));
        pnlRetirar.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 130, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setText("Digite cuánto desea retirar: ");
        pnlRetirar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));
        pnlRetirar.add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 130, -1));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(242, 242, 242));
        jButton1.setText("Regresar");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(this::jButton1ActionPerformed);
        pnlRetirar.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 200, 50));
        jButton1.getAccessibleContext().setAccessibleDescription("250");

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setForeground(new java.awt.Color(242, 242, 242));
        jButton2.setText("Retirar");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.addActionListener(this::jButton2ActionPerformed);
        pnlRetirar.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 200, 50));
        pnlRetirar.add(txtRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 200, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionbancaria/Retirar1.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlRetirar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 350));

        add(pnlRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 400));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtID.setText("");
        txtMonto.setText("");
        txtRespuesta.setText("");
        ventana.layout.show(ventana.panelCards, "panelPrincipal");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MovimientoDao dao = new MovimientoDao();
        int ID = Integer.parseInt(txtID.getText());
       double monto = Double.parseDouble(txtMonto.getText());
       String respuesta=dao.retirar(ID, monto);
       txtRespuesta.setText(respuesta);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlRetirar;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtRespuesta;
    // End of variables declaration//GEN-END:variables
}
