/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gestionbancaria;

/**
 *
 * @author user
 */
public class Transferir extends javax.swing.JPanel {
private VentanaPrincipal ventana;
    /**
     * Creates new form Transferir
     */
    public Transferir(VentanaPrincipal ventana) {
        this.ventana = ventana;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTransferir = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCuenta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRespuesta = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTransferir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 3, 36)); // NOI18N
        jLabel2.setText("Centro de Transferencia");
        pnlTransferir.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel3.setText("Digite la cuenta ID a la cual se le va a realizar el deposito: ");
        pnlTransferir.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));
        pnlTransferir.add(txtCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 270, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel4.setText("Digite cuánto desea depositar: ");
        pnlTransferir.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));
        pnlTransferir.add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 260, -1));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 3, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Regresar");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(this::jButton1ActionPerformed);
        pnlTransferir.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 250, 60));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI Semibold", 3, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(242, 242, 242));
        jButton2.setText("Depositar");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.addActionListener(this::jButton2ActionPerformed);
        pnlTransferir.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 240, 60));

        jScrollPane1.setBorder(new javax.swing.border.MatteBorder(null));

        txtRespuesta.setColumns(20);
        txtRespuesta.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        txtRespuesta.setRows(5);
        jScrollPane1.setViewportView(txtRespuesta);

        pnlTransferir.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 300, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionbancaria/Transferencia1.jpg"))); // NOI18N
        pnlTransferir.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        add(pnlTransferir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 490));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtRespuesta.setText("");
        txtCuenta.setText("");
        txtMonto.setText("");
        ventana.layout.show(ventana.panelCards, "panelPrincipal");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MovimientoDao dao = new MovimientoDao();
        int ID = Integer.parseInt(txtCuenta.getText());
        double monto = Double.parseDouble(txtMonto.getText());
        String respuesta =dao.depositar(ID, monto);
        txtRespuesta.append(respuesta);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlTransferir;
    private javax.swing.JTextField txtCuenta;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextArea txtRespuesta;
    // End of variables declaration//GEN-END:variables
}
