/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gestionbancaria;

/**
 *
 * @author user
 */
public class TransferirCuentas extends javax.swing.JPanel {
private VentanaPrincipal ventana;
    /**
     * Creates new form TransferirCuentas
     */
    public TransferirCuentas(VentanaPrincipal ventana) {
        this.ventana=ventana;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTransferirCuentas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtID1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtID2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtRespuesta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTransferirCuentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Centro de transferencia entre cuentas");
        pnlTransferirCuentas.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Digite el ID de la cuenta origen: ");
        pnlTransferirCuentas.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));
        pnlTransferirCuentas.add(txtID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 260, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setText("Digite el ID de la cuenta origen: ");
        pnlTransferirCuentas.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));
        pnlTransferirCuentas.add(txtID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 260, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(242, 242, 242));
        jLabel5.setText("Digite cuanto desea transferir: ");
        pnlTransferirCuentas.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 270, 20));
        pnlTransferirCuentas.add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 260, -1));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(242, 242, 242));
        jButton1.setText("Regresar");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(this::jButton1ActionPerformed);
        pnlTransferirCuentas.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 240, 50));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(242, 242, 242));
        jButton2.setText("Realizar transferencia");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.addActionListener(this::jButton2ActionPerformed);
        pnlTransferirCuentas.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 240, 50));
        pnlTransferirCuentas.add(txtRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 250, -1));

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionbancaria/TransferirCuentas1.jpg"))); // NOI18N
        pnlTransferirCuentas.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        add(pnlTransferirCuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 480));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtID1.setText("");
        txtID2.setText("");
        txtMonto.setText("");
        txtRespuesta.setText("");
        ventana.layout.show(ventana.panelCards, "panelPrincipal");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MovimientoDao dao = new MovimientoDao();
        int ID1= Integer.parseInt(txtID1.getText());
        int ID2= Integer.parseInt(txtID2.getText());
        double monto = Double.parseDouble(txtMonto.getText());
        String respuesta = dao.transferir(ID1, ID2, monto);
        txtRespuesta.setText(respuesta);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel pnlTransferirCuentas;
    private javax.swing.JTextField txtID1;
    private javax.swing.JTextField txtID2;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtRespuesta;
    // End of variables declaration//GEN-END:variables
}
